### ISSUE TITLE
nmap module not found 

### ISSUE THREAD

**Issue by harshvardhan365** [HalilDeniz/Dosinator#9]
I got this error 

└─$ python dosinator.py -h
Traceback (most recent call last):
  File "/home/kali/Desktop/Dosinator/dosinator.py", line 14, in <module>
    from nmap import nmap
ModuleNotFoundError: No module named 'nmap'

I already installed python3-nmap but still got the same error.

**Comment by HalilDeniz** [comment]
can you run pip install python-nmap on the terminal

**Comment by harshvardhan365** [comment]
yes but it didn't work

**Comment by HalilDeniz** [comment]
Could you join our discord group and share the screenshot of the error you received?
https://discord.gg/nGBpfMHX4u
